apiVersion: v1
kind: Service
metadata:
  name: health-check-service
spec:
  selector:
    app: health-check-system
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000  # Adjust if your script uses a different port
  type: LoadBalancer
